analyzer:
  errors:
    lines_longer_than_80_chars: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - deni/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - lines_longer_than_80_chars
